Scanner updates
sensorfleet/pscan pull request #10
Opened 2022-05-25 11:30 UTC by jtt

* Remove duplicates from ports
   *  If same port is given multiple times, it is scanned only once.
 * Simplify port iterator
 * Start scanning for multiple hosts in parallel instead of focusing scanning on single host at a time.

2022-08-16 09:41 UTC, atonkyra requested changes
Consider removing the leftover commented function.

2022-08-16 09:41 UTC, atonkyra commented on src/ports.rs
> +    // }
Any reason why this is kept here as commented?

2022-09-16 07:56 UTC, jtt commented on src/ports.rs
> +    // }
done

2022-09-16 08:53 UTC, mkorkalo commented on README.md
> +            Number of hosts to scan concurrently. Can be used to limit the number of hoststo scan at
typo

2022-09-16 11:31 UTC, jtt commented on README.md
> +            Number of hosts to scan concurrently. Can be used to limit the number of hoststo scan at
Fixed

2022-09-19 09:50 UTC, atonkyra approved these changes

2022-09-19 10:22 UTC, merged